// Раскладки клавиатуры для ввода без переключения раскладки ОС.
// Ключ — event.code (физическая клавиша), значение — [строчный, заглавный].

export const LAYOUT_LA: Record<string, [string, string]> = {
    KeyQ: ["q", "Q"],
    KeyW: ["w", "W"],
    KeyE: ["e", "E"],
    KeyR: ["r", "R"],
    KeyT: ["t", "T"],
    KeyY: ["y", "Y"],
    KeyU: ["u", "U"],
    KeyI: ["i", "I"],
    KeyO: ["o", "O"],
    KeyP: ["p", "P"],
    BracketLeft: ["[", "{"],
    BracketRight: ["]", "}"],

    KeyA: ["a", "A"],
    KeyS: ["s", "S"],
    KeyD: ["d", "D"],
    KeyF: ["f", "F"],
    KeyG: ["g", "G"],
    KeyH: ["h", "H"],
    KeyJ: ["j", "J"],
    KeyK: ["k", "K"],
    KeyL: ["l", "L"],
    Semicolon: [";", ":"],
    Quote: ["'", "\""],

    KeyZ: ["z", "Z"],
    KeyX: ["x", "X"],
    KeyC: ["c", "C"],
    KeyV: ["v", "V"],
    KeyB: ["b", "B"],
    KeyN: ["n", "N"],
    KeyM: ["m", "M"],
    Comma: [",", "<"],
    Period: [".", ">"],
    Slash: ["/", "?"],
};

export const LAYOUT_GR: Record<string, [string, string]> = {
    // Верхний ряд
    KeyQ: [";", ":"],
    KeyW: ["ς", "Σ"],
    KeyE: ["ε", "Ε"],
    KeyR: ["ρ", "Ρ"],
    KeyT: ["τ", "Τ"],
    KeyY: ["υ", "Υ"],
    KeyU: ["θ", "Θ"],
    KeyI: ["ι", "Ι"],
    KeyO: ["ο", "Ο"],
    KeyP: ["π", "Π"],
    BracketLeft: ["[", "{"],
    BracketRight: ["]", "}"],

    // Средний ряд
    KeyA: ["α", "Α"],
    KeyS: ["σ", "Σ"],
    KeyD: ["δ", "Δ"],
    KeyF: ["φ", "Φ"],
    KeyG: ["γ", "Γ"],
    KeyH: ["η", "Η"],
    KeyJ: ["ξ", "Ξ"],
    KeyK: ["κ", "Κ"],
    KeyL: ["λ", "Λ"],
    Semicolon: ["΄", "¨"],
    Quote: ["'", "\""],

    // Нижний ряд
    KeyZ: ["ζ", "Ζ"],
    KeyX: ["χ", "Χ"],
    KeyC: ["ψ", "Ψ"],
    KeyV: ["ω", "Ω"],
    KeyB: ["β", "Β"],
    KeyN: ["ν", "Ν"],
    KeyM: ["μ", "Μ"],
    Comma: [",", "<"],
    Period: [".", ">"],
    Slash: ["/", "?"],
};

export const LAYOUT_RU: Record<string, [string, string]> = {
    // Верхний ряд
    KeyQ: ["й", "Й"],
    KeyW: ["ц", "Ц"],
    KeyE: ["у", "У"],
    KeyR: ["к", "К"],
    KeyT: ["е", "Е"],
    KeyY: ["н", "Н"],
    KeyU: ["г", "Г"],
    KeyI: ["ш", "Ш"],
    KeyO: ["щ", "Щ"],
    KeyP: ["з", "З"],
    BracketLeft: ["х", "Х"],
    BracketRight: ["ъ", "Ъ"],

    // Средний ряд
    KeyA: ["ф", "Ф"],
    KeyS: ["ы", "Ы"],
    KeyD: ["в", "В"],
    KeyF: ["а", "А"],
    KeyG: ["п", "П"],
    KeyH: ["р", "Р"],
    KeyJ: ["о", "О"],
    KeyK: ["л", "Л"],
    KeyL: ["д", "Д"],
    Semicolon: ["ж", "Ж"],
    Quote: ["э", "Э"],

    // Нижний ряд
    KeyZ: ["я", "Я"],
    KeyX: ["ч", "Ч"],
    KeyC: ["с", "С"],
    KeyV: ["м", "М"],
    KeyB: ["и", "И"],
    KeyN: ["т", "Т"],
    KeyM: ["ь", "Ь"],
    Comma: ["б", "Б"],
    Period: ["ю", "Ю"],
    Slash: [".", ","],
};
